// CypherBeam — Word→Emoji Dictionary
// 500+ mappings: DE + EN + Rap Slang + Sentiment

const EMOJI_DICT = {
  // ═══════════════════════════════════════
  // DEUTSCH — Nomen
  // ═══════════════════════════════════════
  "feuer": "🔥", "geld": "💰", "krone": "👑", "mic": "🎤", "mikrofon": "🎤",
  "herz": "❤️", "liebe": "❤️", "stern": "⭐", "sterne": "⭐", "mond": "🌙",
  "sonne": "☀️", "welt": "🌍", "erde": "🌍", "himmel": "🌌", "nacht": "🌙",
  "tag": "☀️", "stadt": "🏙️", "strasse": "🛣️", "straße": "🛣️",
  "auto": "🚗", "zug": "🚂", "flugzeug": "✈️", "schiff": "🚢",
  "haus": "🏠", "schloss": "🏰", "turm": "🗼", "brücke": "🌉",
  "berg": "⛰️", "meer": "🌊", "fluss": "🏞️", "wald": "🌲", "baum": "🌳",
  "blume": "🌺", "rose": "🌹", "blatt": "🍃", "regen": "🌧️",
  "schnee": "❄️", "blitz": "⚡", "donner": "⚡", "sturm": "🌪️",
  "wolf": "🐺", "löwe": "🦁", "adler": "🦅", "drache": "🐉", "schlange": "🐍",
  "hund": "🐕", "katze": "🐈", "vogel": "🐦", "fisch": "🐟",
  "auge": "👁️", "hand": "✋", "faust": "✊", "finger": "👆",
  "kopf": "🗣️", "stimme": "🗣️", "bein": "🦵", "blut": "🩸",
  "waffe": "🔫", "schwert": "⚔️", "messer": "🔪", "schild": "🛡️",
  "bombe": "💣", "rakete": "🚀", "flagge": "🏳️",
  "king": "👑", "könig": "👑", "königin": "👸", "queen": "👸",
  "diamant": "💎", "gold": "🥇", "silber": "🥈", "juwel": "💎",
  "kette": "⛓️", "ring": "💍", "uhr": "⌚",
  "musik": "🎵", "beat": "🥁", "bass": "🔊", "melodie": "🎶",
  "gitarre": "🎸", "klavier": "🎹", "trommel": "🥁",
  "bier": "🍺", "wein": "🍷", "champagner": "🥂", "whisky": "🥃",
  "pizza": "🍕", "brot": "🍞", "fleisch": "🥩", "obst": "🍎",
  "kuchen": "🎂", "eis": "🍦",
  "fussball": "⚽", "basketball": "🏀", "boxen": "🥊",
  "trophy": "🏆", "trophäe": "🏆", "medaille": "🏅", "pokal": "🏆",
  "gewinner": "🏆", "sieger": "🏆",
  "kind": "👶", "baby": "👶", "mann": "👨", "frau": "👩",
  "bruder": "👊", "schwester": "👩", "familie": "👨‍👩‍👧‍👦",
  "freund": "🤝", "feind": "👿", "legende": "🐐",
  "traum": "💭", "seele": "👻", "geist": "👻",
  "engel": "😇", "teufel": "😈", "dämon": "👿",
  "paradies": "🏝️", "hölle": "🔥",
  "freiheit": "🕊️", "friede": "☮️", "frieden": "☮️",
  "krieg": "⚔️", "kampf": "💪", "sieg": "🏆",
  "zeit": "⏳", "zukunft": "🔮", "vergangenheit": "⏪",
  "wahrheit": "💯", "lüge": "🤥",
  "schmerz": "💔", "tod": "💀", "leben": "🌱",
  "hoffnung": "🌈", "angst": "😨", "mut": "🦁",
  "kraft": "💪", "macht": "⚡", "energie": "⚡",
  "gott": "🙏", "beten": "🙏", "kirche": "⛪",
  "dollar": "💵", "euro": "💶", "bitcoin": "₿",
  "telefon": "📱", "handy": "📱", "computer": "💻",
  "kamera": "📷", "foto": "📸", "bild": "🖼️",
  "buch": "📖", "brief": "✉️", "stift": "✏️",
  "schlüssel": "🔑", "tür": "🚪", "fenster": "🪟",
  "feuerwerk": "🎆", "party": "🎉", "geschenk": "🎁",
  "maske": "🎭", "clown": "🤡", "ghost": "👻",

  // ═══════════════════════════════════════
  // DEUTSCH — Verben
  // ═══════════════════════════════════════
  "fliegen": "✈️", "fliege": "✈️", "rennen": "🏃", "renne": "🏃",
  "kämpfen": "⚔️", "kämpfe": "⚔️", "tanzen": "💃", "tanze": "💃",
  "singen": "🎤", "singe": "🎤", "rappen": "🎤", "rappe": "🎤",
  "lachen": "😂", "lache": "😂", "weinen": "😢", "weine": "😢",
  "lieben": "❤️", "hassen": "🖤", "hasse": "🖤",
  "schlafen": "😴", "schlafe": "😴", "träumen": "💭", "träume": "💭",
  "essen": "🍽️", "esse": "🍽️", "trinken": "🍷", "trinke": "🍷",
  "rauchen": "🚬", "rauche": "🚬",
  "schiessen": "🔫", "schießen": "🔫", "töten": "💀",
  "brennen": "🔥", "brenne": "🔥", "leuchten": "✨", "leuchte": "✨",
  "fallen": "⬇️", "falle": "⬇️", "steigen": "⬆️", "steige": "⬆️",
  "bauen": "🏗️", "zerstören": "💥",
  "regieren": "👑", "herrschen": "👑",
  "gewinnen": "🏆", "verlieren": "😞",
  "springen": "🦘", "schwimmen": "🏊",
  "fahren": "🚗", "reisen": "🧳",
  "spielen": "🎮", "arbeiten": "💼",
  "denken": "🧠", "wissen": "🧠", "fühlen": "💗",

  // ═══════════════════════════════════════
  // DEUTSCH — Adjektive / Stimmung
  // ═══════════════════════════════════════
  "krass": "💥", "hart": "💪", "stark": "💪", "schnell": "⚡",
  "geil": "🔥", "nice": "✨", "wild": "🐺", "frei": "🕊️",
  "kalt": "🥶", "heiß": "🥵", "heiss": "🥵",
  "groß": "🏔️", "gross": "🏔️", "klein": "🐜",
  "laut": "📢", "leise": "🤫",
  "reich": "💰", "arm": "😞",
  "schön": "✨", "hässlich": "👹",
  "gut": "👍", "schlecht": "👎", "böse": "😈",
  "traurig": "😢", "wütend": "😡", "glücklich": "😊",
  "verrückt": "🤪", "crazy": "🤪",
  "dunkel": "🌑", "hell": "🌟",
  "echt": "💯", "fake": "🤥", "real": "💯",
  "heilig": "🙏", "verflucht": "☠️",
  "einsam": "🥀", "allein": "🥀",
  "hungrig": "🍽️", "müde": "😴", "wach": "👁️",
  "stolz": "🦁", "demütig": "🙏",
  "giftig": "☠️", "toxic": "☠️",

  // ═══════════════════════════════════════
  // ENGLISH — Nouns
  // ═══════════════════════════════════════
  "fire": "🔥", "money": "💰", "crown": "👑", "microphone": "🎤",
  "heart": "❤️", "love": "❤️", "star": "⭐", "stars": "⭐", "moon": "🌙",
  "sun": "☀️", "world": "🌍", "earth": "🌍", "sky": "🌌",
  "night": "🌙", "day": "☀️", "city": "🏙️", "street": "🛣️",
  "car": "🚗", "ride": "🚗", "whip": "🚗",
  "house": "🏠", "home": "🏠", "castle": "🏰", "tower": "🗼",
  "mountain": "⛰️", "ocean": "🌊", "sea": "🌊", "river": "🏞️",
  "forest": "🌲", "tree": "🌳", "flower": "🌺", "rain": "🌧️",
  "snow": "❄️", "lightning": "⚡", "thunder": "⚡", "storm": "🌪️",
  "wolf": "🐺", "lion": "🦁", "eagle": "🦅", "dragon": "🐉", "snake": "🐍",
  "dog": "🐕", "cat": "🐈", "bird": "🐦", "fish": "🐟", "goat": "🐐",
  "eye": "👁️", "eyes": "👁️", "hand": "✋", "hands": "✋",
  "fist": "✊", "blood": "🩸", "bone": "🦴", "skull": "💀",
  "gun": "🔫", "sword": "⚔️", "knife": "🔪", "shield": "🛡️",
  "bomb": "💣", "rocket": "🚀", "flag": "🏳️",
  "diamond": "💎", "diamonds": "💎", "chain": "⛓️", "chains": "⛓️",
  "watch": "⌚", "ring": "💍",
  "music": "🎵", "song": "🎵", "melody": "🎶", "drum": "🥁", "drums": "🥁",
  "guitar": "🎸", "piano": "🎹",
  "beer": "🍺", "wine": "🍷", "champagne": "🥂", "drink": "🍷",
  "bread": "💰", "cake": "🎂", "ice": "🧊",
  "game": "🎮", "ball": "⚽", "trophy": "🏆", "medal": "🏅",
  "winner": "🏆", "champion": "🏆", "legend": "🐐",
  "child": "👶", "kid": "👶", "man": "👨", "woman": "👩",
  "brother": "👊", "sister": "👩", "family": "👨‍👩‍👧‍👦",
  "friend": "🤝", "enemy": "👿", "crew": "👥", "squad": "👥", "gang": "👥",
  "dream": "💭", "dreams": "💭", "soul": "👻", "spirit": "👻",
  "angel": "😇", "devil": "😈", "demon": "👿", "god": "🙏",
  "heaven": "☁️", "hell": "🔥", "paradise": "🏝️",
  "freedom": "🕊️", "peace": "☮️", "war": "⚔️",
  "fight": "💪", "battle": "⚔️", "victory": "🏆",
  "time": "⏳", "future": "🔮", "past": "⏪",
  "truth": "💯", "lie": "🤥", "lies": "🤥",
  "pain": "💔", "death": "💀", "life": "🌱",
  "hope": "🌈", "fear": "😨", "courage": "🦁",
  "power": "⚡", "strength": "💪", "energy": "⚡", "force": "💪",
  "prayer": "🙏", "church": "⛪", "cross": "✝️",
  "dollar": "💵", "cash": "💵", "check": "💵",
  "phone": "📱", "camera": "📷", "book": "📖",
  "key": "🔑", "keys": "🔑", "door": "🚪", "lock": "🔒",
  "fireworks": "🎆", "gift": "🎁",
  "mask": "🎭", "ghost": "👻", "zombie": "🧟",
  "brain": "🧠", "mind": "🧠", "genius": "🧠",
  "king": "👑", "queen": "👸", "prince": "🤴", "princess": "👸",
  "throne": "🪑", "empire": "🏰",
  "jungle": "🌴", "desert": "🏜️", "island": "🏝️",
  "sunrise": "🌅", "sunset": "🌇", "rainbow": "🌈",
  "butterfly": "🦋", "bee": "🐝", "spider": "🕷️",
  "shark": "🦈", "whale": "🐋", "bear": "🐻",
  "flame": "🔥", "flames": "🔥", "smoke": "💨",
  "mirror": "🪞", "shadow": "👤", "shadows": "👤",
  "bridge": "🌉", "road": "🛣️", "path": "🛤️",
  "light": "💡", "darkness": "🌑",
  "wave": "🌊", "waves": "🌊", "wind": "💨",
  "tears": "😢", "smile": "😊",
  "hustle": "💪", "grind": "⚙️",

  // ═══════════════════════════════════════
  // ENGLISH — Verbs
  // ═══════════════════════════════════════
  "fly": "✈️", "flying": "✈️", "run": "🏃", "running": "🏃",
  "fight": "⚔️", "fighting": "⚔️", "dance": "💃", "dancing": "💃",
  "sing": "🎤", "singing": "🎤", "rap": "🎤", "rapping": "🎤",
  "spit": "🔥", "spitting": "🔥",
  "laugh": "😂", "laughing": "😂", "cry": "😢", "crying": "😢",
  "hate": "🖤", "hating": "🖤",
  "sleep": "😴", "sleeping": "😴",
  "eat": "🍽️", "eating": "🍽️",
  "smoke": "🚬", "smoking": "🚬",
  "shoot": "🔫", "shooting": "🔫", "kill": "💀", "killing": "💀",
  "burn": "🔥", "burning": "🔥", "shine": "✨", "shining": "✨",
  "glow": "✨", "glowing": "✨",
  "fall": "⬇️", "falling": "⬇️", "rise": "⬆️", "rising": "⬆️",
  "build": "🏗️", "building": "🏗️", "destroy": "💥",
  "rule": "👑", "ruling": "👑", "reign": "👑",
  "win": "🏆", "winning": "🏆", "lose": "😞", "losing": "😞",
  "jump": "🦘", "jumping": "🦘", "swim": "🏊", "swimming": "🏊",
  "drive": "🚗", "driving": "🚗", "travel": "🧳",
  "play": "🎮", "playing": "🎮", "work": "💼", "working": "💼",
  "think": "🧠", "thinking": "🧠", "feel": "💗", "feeling": "💗",
  "pray": "🙏", "praying": "🙏",
  "flex": "💪", "flexing": "💪",
  "drip": "💧", "dripping": "💧",
  "bang": "💥", "pop": "💥",
  "roll": "🎲", "rolling": "🎲",
  "slide": "🛝", "sliding": "🛝",
  "grind": "⚙️", "grinding": "⚙️",
  "blow": "💨", "blowing": "💨",
  "pull": "🏋️", "push": "💪",
  "stack": "💰", "stacking": "💰",
  "trap": "🪤",

  // ═══════════════════════════════════════
  // ENGLISH — Adjectives / Mood
  // ═══════════════════════════════════════
  "hard": "💪", "strong": "💪", "fast": "⚡", "quick": "⚡",
  "hot": "🥵", "cold": "🥶", "cool": "😎",
  "big": "🏔️", "small": "🐜", "little": "🐜", "huge": "🏔️",
  "loud": "📢", "quiet": "🤫", "silent": "🤫",
  "rich": "💰", "poor": "😞", "broke": "😞",
  "beautiful": "✨", "ugly": "👹", "pretty": "✨",
  "good": "👍", "bad": "👎", "evil": "😈", "wicked": "😈",
  "sad": "😢", "angry": "😡", "mad": "😡", "happy": "😊",
  "crazy": "🤪", "insane": "🤪", "wild": "🐺", "savage": "🐺",
  "dark": "🌑", "bright": "🌟",
  "real": "💯", "fake": "🤥", "true": "💯",
  "holy": "🙏", "cursed": "☠️", "blessed": "🙏",
  "lonely": "🥀", "alone": "🥀",
  "hungry": "🍽️", "tired": "😴",
  "proud": "🦁", "humble": "🙏",
  "toxic": "☠️", "sick": "🤒", "ill": "🔥",
  "fresh": "🆕", "raw": "🩸",
  "deep": "🌊", "high": "⬆️", "low": "⬇️",
  "dead": "💀", "alive": "🌱",
  "free": "🕊️", "trapped": "🔒",
  "legendary": "🐐", "iconic": "⭐",
  "golden": "🥇", "silver": "🥈",
  "immortal": "♾️", "infinite": "♾️", "eternal": "♾️",
  "dangerous": "⚠️", "lethal": "☠️",
  "royal": "👑", "supreme": "👑",
  "dirty": "🗑️", "clean": "✨", "pure": "✨",
  "heavy": "🏋️", "massive": "🏔️",
  "lit": "🔥", "dope": "🔥", "fire": "🔥", "sick": "🔥",

  // ═══════════════════════════════════════
  // RAP SLANG (DE + EN)
  // ═══════════════════════════════════════
  "drip": "💧", "swag": "😎", "bling": "💎", "ice": "🧊💎",
  "bars": "📝", "flow": "🌊", "freestyle": "🎤", "cypher": "🔥🎤",
  "hood": "🏘️", "block": "🏘️", "ghetto": "🏚️",
  "trap": "🪤", "plug": "🔌", "hustle": "💪",
  "homie": "🤝", "bro": "👊", "brudi": "👊", "digga": "👊",
  "alter": "👊", "bruder": "👊", "habibi": "🤝",
  "ayo": "📢", "yo": "📢", "yeah": "🙌", "jah": "🙌",
  "geil": "🔥", "mega": "💥", "hammer": "🔨",
  "affe": "🐒", "monkey": "🐒", "beast": "👹", "biest": "👹",
  "flex": "💪", "drauf": "💪", "baba": "👑",
  "hype": "🔥", "vibe": "🎵", "vibes": "🎵",
  "gang": "👥", "click": "👥", "clique": "👥",
  "mula": "💰", "guap": "💰", "bands": "💰", "racks": "💰",
  "whip": "🚗", "ride": "🚗", "beamer": "🚗",
  "strap": "🔫", "heat": "🔫", "piece": "🔫",
  "banger": "💥🎵", "anthem": "🎵", "hit": "💥",
  "goat": "🐐", "GOAT": "🐐", "g.o.a.t": "🐐",
  "cap": "🧢", "no cap": "💯", "nocap": "💯",
  "sus": "🤔", "lowkey": "🤫", "highkey": "📢",
  "fam": "👨‍👩‍👧‍👦", "crib": "🏠", "spot": "📍",
  "weed": "🌿", "kush": "🌿", "gas": "⛽",
  "drip": "💧💎", "sauce": "🔥", "steez": "😎",
  "clap": "👏", "slap": "👋", "snap": "🫰",
  "cheese": "💰", "paper": "💵", "stacks": "💰",
  "ice": "🧊💎", "froze": "🥶", "frozen": "🥶",
  "chain": "⛓️💎", "rolex": "⌚", "rollie": "⌚",
  "bentley": "🚗💎", "lambo": "🏎️", "porsche": "🏎️", "benz": "🚗",
  "studio": "🎙️", "booth": "🎙️", "stage": "🎤",
  "mixtape": "📼", "album": "💿", "track": "🎵", "verse": "📝",
  "punchline": "💥", "wordplay": "🧠", "metapher": "🎭",
  "wack": "🗑️", "trash": "🗑️", "corny": "🌽",
  "clutch": "💪", "valid": "✅", "bet": "🤝",
  "facts": "💯", "period": "💯", "word": "💯",
  "ghostwriter": "👻✏️", "beef": "🥩😤", "diss": "😤",
  "snitch": "🐀", "rat": "🐀", "snake": "🐍",
  "plug": "🔌", "connect": "🤝",
  "turned up": "🔊", "turnt": "🔊", "lit": "🔥",
  "slay": "⚔️✨", "bodied": "💀", "murdered": "💀",
  "crispy": "✨", "cleaner": "✨", "dripped": "💧",

  // ═══════════════════════════════════════
  // FRENCH — Common Words
  // ═══════════════════════════════════════
  "amour": "❤️", "coeur": "❤️", "feu": "🔥", "argent": "💰",
  "roi": "👑", "reine": "👸", "monde": "🌍", "vie": "🌱",
  "mort": "💀", "guerre": "⚔️", "paix": "☮️",
  "soleil": "☀️", "lune": "🌙", "nuit": "🌙", "jour": "☀️",
  "rêve": "💭", "espoir": "🌈", "peur": "😨",
  "liberté": "🕊️", "force": "💪", "victoire": "🏆",
  "musique": "🎵", "chanson": "🎵",

  // ═══════════════════════════════════════
  // SPANISH — Common Words
  // ═══════════════════════════════════════
  "amor": "❤️", "corazón": "❤️", "fuego": "🔥", "dinero": "💰",
  "rey": "👑", "reina": "👸", "mundo": "🌍", "vida": "🌱",
  "muerte": "💀", "guerra": "⚔️", "paz": "☮️",
  "sol": "☀️", "luna": "🌙", "noche": "🌙", "dia": "☀️",
  "sueño": "💭", "esperanza": "🌈", "miedo": "😨",
  "libertad": "🕊️", "fuerza": "💪", "victoria": "🏆",
  "música": "🎵", "canción": "🎵",

  // ═══════════════════════════════════════
  // SENTIMENT COMBOS (multi-emoji)
  // ═══════════════════════════════════════
  "ich bin der king": "👑🔥💯",
  "auf der bühne": "🎤🎵💡",
  "in der hood": "🏘️💪🔥",
  "ganz oben": "⬆️👑🌟",
  "ganz unten": "⬇️😞💔",
  "nummer eins": "🥇🏆💯",
  "number one": "🥇🏆💯",
  "run the game": "🏃👑🎮",
  "on top": "⬆️👑",
  "ride or die": "🚗💀❤️",
  "day one": "🌅💯",
  "real talk": "💯🗣️",
  "big boss": "👑💼",
  "old school": "📼🎵",
  "new school": "🆕🎵",
  "make it rain": "💰🌧️",
  "drop the mic": "🎤⬇️",
  "hold it down": "💪✊",
  "keep it real": "💯✊",
  "stay woke": "👁️💯",
  "level up": "⬆️🎮",
  "game over": "🎮💀",
  "straight fire": "🔥🔥🔥",
};

// Sentiment analysis keywords
const POSITIVE_WORDS = new Set([
  "liebe", "love", "sieg", "victory", "win", "gewinner", "champion", "legend",
  "hoffnung", "hope", "freude", "joy", "happy", "glücklich", "schön", "beautiful",
  "frei", "free", "freiheit", "freedom", "frieden", "peace", "paradies", "paradise",
  "heaven", "himmel", "engel", "angel", "blessed", "heilig", "stolz", "proud",
  "gold", "golden", "diamant", "diamond", "krone", "crown", "king", "queen",
  "stark", "strong", "kraft", "power", "mut", "courage", "legende", "legendary",
  "lit", "fire", "dope", "goat", "banger", "slay", "valid", "facts",
  "shine", "glow", "rise", "fly", "dream", "build", "create",
  "real", "echt", "true", "wahrheit", "truth", "rainbow", "regenbogen",
  "familia", "family", "brother", "homie", "crew", "squad",
]);

const NEGATIVE_WORDS = new Set([
  "schmerz", "pain", "tod", "death", "dead", "hass", "hate", "krieg", "war",
  "angst", "fear", "lüge", "lie", "fake", "traurig", "sad", "wütend", "angry",
  "böse", "evil", "hölle", "hell", "teufel", "devil", "demon", "dämon",
  "einsam", "lonely", "alone", "allein", "dunkel", "dark", "darkness",
  "gift", "toxic", "giftig", "verflucht", "cursed", "verlieren", "lose",
  "fallen", "fall", "zerstören", "destroy", "kill", "töten",
  "blut", "blood", "skull", "bones", "grave",
  "snake", "snitch", "rat", "trash", "wack",
  "broke", "poor", "arm", "trapped", "locked",
  "cry", "tears", "weinen",
]);

// Export for use in app.js
if (typeof window !== "undefined") {
  window.EMOJI_DICT = EMOJI_DICT;
  window.POSITIVE_WORDS = POSITIVE_WORDS;
  window.NEGATIVE_WORDS = NEGATIVE_WORDS;
}
